#定义端口
server:
  port: 8081
  servlet:
    context-path: /
#连接数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 131425
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
#      idle-timeout：连接在空闲时间达到指定值后会被断开，默认为60000毫秒（即60秒）。
#      maximum-pool-size：连接池中最大可同时存在的连接数，默认为30个。
#      minimum-idle：连接池中保持的最小空闲连接数，默认为10个。
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  thymeleaf:
    cache: true

#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.qtds.domain
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.qtds: debug


  #阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI4GCH1vX6DKqJWxd6nEuW
    accessKeySecret: yBshYweHOpqDuhCArrVHwIiBKpyqSL
    bucketName: web-tlias
